Features/tasks
Dev-incubator/DIMS.UI-13 pull request #12
Opened 2021-04-25 08:28 UTC by AlexanderRusak

Reworked and fixed mistakes in previous pr

2021-04-28 16:54 UTC, maximsan requested changes
Hello. Please read my comments from closed p-r. Looks like you still have the same issues as I noted there.

2021-04-28 16:54 UTC, maximsan commented on src/components/Footer/Footer.jsx
> +          iconComponent={<BsEgg size={FONTS_SIZE.ICON_FOOTER} color={COLORS.WHITE} />}
move this props `size={FONTS_SIZE.ICON_FOOTER} color={COLORS.WHITE}` to you custom Icon component, because u repeat here the same 4 times

2021-04-28 16:54 UTC, maximsan commented on src/components/Auth/Auth.js
> +};
add unit-tests

2021-04-28 16:54 UTC, maximsan commented on src/components/Auth/Auth.js
> +};
add unit-tests

2021-04-28 16:54 UTC, maximsan commented on src/components/Auth/Auth.js
> +  const re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
it should be located outside or in constants

2021-04-28 16:54 UTC, maximsan commented on src/components/Modal/DeleteModal/DeleteModal.module.css
> +.DeleteModal p {
follow one naming - `camelCase` or if you want to name classes different name it everywhere as `DeleteModal`

2021-04-28 16:54 UTC, maximsan commented on src/components/Modal/DeleteModal/DeleteModal.module.css
> +    border: 1px solid #000;
use `css variables` for colors, I've already said it in previous p-r

2021-04-28 16:54 UTC, maximsan commented on src/components/Auth/Auth.js
> +  let isValid = true;
Did you read my comments from closed p-r ? please, read them.

2021-04-28 16:54 UTC, maximsan commented on src/components/Modal/DeleteModal/DeleteModal.jsx
> +      {getDeleteModalTemplate(title, onClose, item, onDelete)}
I don't actually see any profit of this approach with `getDeleteModalTemplate`. it's not reusable component.

2021-04-28 16:54 UTC, maximsan commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const el = toLowerCaseFirstLetter(toTrim(value.target.attributes[1].nodeValue));
why do you need to get `nodeValue` here ? it can be solved easier

2021-04-29 18:23 UTC, maximsan requested changes
Hello! I left some comments.

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.module.css
> +.Tasks {
here is the same question about naming.

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +            {this.getButton('delete', 'Delete', `${classes.delete}`)}
create component, not method

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +        {this.getHeader()}
create component, not method

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +        data: tasks,
you can use short object props here `this.setState({ data })`

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +        this.openModalHandler(type);
create method

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +    <Button onClick={() => this.openModalHandler(modalType)} className={styles}>
create method

2021-04-29 18:23 UTC, maximsan commented on src/pages/Tasks/TableStyle.module.css
> +    background-color: #F0AD4E;
name colors everywhere the same using small or big letters. it's just convenient to use 1 approach everywhere.

2021-04-29 18:23 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +      <Button key={button.type} className={button.style} onClick={() => this.openModal(button.type, elementIndex)}>
create method `onClick={onClick}`

2021-04-29 18:23 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +        <li className={classes.actions}>{this.getButtonActions(index)}</li>
create component, not method

2021-04-29 18:23 UTC, maximsan commented on src/components/UI/CheckBox/Checkbox.jsx
> +      users: [...props.users],
use ComponentDidmount for this, we don't spread data in constructor

2021-04-29 18:23 UTC, maximsan commented on src/components/Modal/modalHelpers/helpers.jsx
> +    return str.trim().replace(/\s/g, '');
add unit-tests

2021-04-29 18:23 UTC, maximsan commented on src/components/Modal/TasksModal/TasksModal.jsx
> +      fakeUsers: [...newUsers],
no need to do this

2021-04-29 18:23 UTC, maximsan commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    await createNewUser(email, '          ');
why do you do it `'          '`?

2021-04-29 18:48 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    await createNewUser(email, '          ');
set init password

2021-04-29 19:56 UTC, maximsan commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    await createNewUser(email, '          ');
It's not programming approach, we don't use magic symbols, long empty strings and other unclear things

2021-04-29 20:06 UTC, AlexanderRusak commented on src/components/Footer/Footer.jsx
> +          iconComponent={<BsEgg size={FONTS_SIZE.ICON_FOOTER} color={COLORS.WHITE} />}
reworked and made new component

2021-04-29 20:09 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  const re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
removed

2021-04-29 20:26 UTC, AlexanderRusak commented on src/components/Modal/DeleteModal/DeleteModal.module.css
> +.DeleteModal p {
added

2021-04-29 20:31 UTC, AlexanderRusak commented on src/components/Modal/DeleteModal/DeleteModal.module.css
> +    border: 1px solid #000;
added

2021-04-30 22:14 UTC, AlexanderRusak commented on src/components/Modal/DeleteModal/DeleteModal.jsx
> +      {getDeleteModalTemplate(title, onClose, item, onDelete)}
Just modal

2021-04-30 22:17 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.module.css
> +.Tasks {
this is css and class in jsx has own naming like class Task .....   className={Task,module.....}

2021-04-30 22:50 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +            {this.getButton('delete', 'Delete', `${classes.delete}`)}
created

2021-04-30 22:50 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        {this.getHeader()}
created

2021-04-30 22:51 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        data: tasks,
oh sure

2021-04-30 22:53 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        this.openModalHandler(type);
it's a method or i don't understand you

2021-04-30 22:54 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +    <Button onClick={() => this.openModalHandler(modalType)} className={styles}>
created method and removed that

2021-04-30 22:55 UTC, AlexanderRusak commented on src/pages/Tasks/TableStyle.module.css
> +    background-color: #F0AD4E;
done

2021-04-30 23:05 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +      <Button key={button.type} className={button.style} onClick={() => this.openModal(button.type, elementIndex)}>
this method created inside MembersTrack. Do you advise me to get onClick from props?

2021-04-30 23:11 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +        <li className={classes.actions}>{this.getButtonActions(index)}</li>
In this method i render button but inside i;m used to component

2021-04-30 23:15 UTC, AlexanderRusak commented on src/components/UI/CheckBox/Checkbox.jsx
> +      users: [...props.users],
okey i undersand

2021-04-30 23:16 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +      fakeUsers: [...newUsers],
i removed that

2021-04-30 23:19 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    await createNewUser(email, '          ');
ok i used to user email

2021-05-01 20:31 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +        this.openModalHandler(type);
`onClick={onClick}`. I've already said it 10 times at least.

2021-05-01 20:34 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +        <li className={classes.actions}>{this.getButtonActions(index)}</li>
`this.getButtonActions(index)` should be `<ActionButton />` component

2021-05-01 20:41 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +      <Button key={button.type} className={button.style} onClick={() => this.openModal(button.type, elementIndex)}>
no I mean `
const onClick= () => this.openModal(button.type, elementIndex)
onClick={onClick}
`

2021-05-01 22:11 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +};
added

2021-05-01 22:11 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +};
remove to helpers and add unit test

2021-05-01 22:40 UTC, AlexanderRusak commented on src/components/Modal/modalHelpers/helpers.jsx
> +    return str.trim().replace(/\s/g, '');
added

2021-05-01 22:41 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  let isValid = true;
Yes i have read and rebuilded

2021-05-02 18:08 UTC, maximsan requested changes
Please read this example https://github.com/Dev-incubator/Wiki-UI/blob/master/testing/simpleUnitTestAAA.js
All tests should be written following this approach.

2021-05-03 09:07 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        this.openModalHandler(type);
i need to know what kind of modal window i have chosen

2021-05-03 10:10 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        this.openModalHandler(type);
okay

2021-05-03 10:14 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +      <Button key={button.type} className={button.style} onClick={() => this.openModal(button.type, elementIndex)}>
removed

2021-05-03 10:15 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  const re = regEmail;
really stupid thing

2021-05-03 10:15 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  const re = regEmail;
removed

2021-05-03 18:32 UTC, Dev1LtJ submitted a review, later dismissed
Nothing very criminal was found. Left some comments. Approved.

2021-05-03 18:32 UTC, Dev1LtJ commented on src/components/LinkItem/LinkItem.jsx
> +};
Your always need an icon and/or link in this component. It will be no sense of this component otherwise.

2021-05-03 20:22 UTC, AlexanderRusak commented on src/components/LinkItem/LinkItem.jsx
> +};
Have you meant local icon and link?

2021-05-03 20:22 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  return re.test(String(email).toLowerCase());
rewritten

2021-05-04 18:33 UTC, maximsan requested changes
Fix tests please

2021-05-04 19:24 UTC, AlexanderRusak commented on src/components/Auth/Auth.test.js
> +        expect(validateControl(actual, data)).toBeTruthy()
removed

2021-05-04 19:26 UTC, AlexanderRusak commented on src/components/Auth/Auth.test.js
> +        expect(validateControl(fake, { required: true, email: true })).toBeFalsy()
removed

2021-05-04 19:27 UTC, AlexanderRusak commented on src/components/Auth/Auth.test.js
> +        expect(validateControl(fake, undefined)).toBe(false);
used to

2021-05-04 19:41 UTC, AlexanderRusak commented on src/components/Auth/Auth.test.js
> +    const exceded = actual.trim().length;
rewritten

2021-05-04 19:59 UTC, maximsan submitted a review, later dismissed
Looks ok. Please, check why your code is not formatted. I see a lot of indents in your tests.

2021-05-05 07:33 UTC, AlexanderRusak commented on src/components/Auth/Auth.test.js
> +        expect(validateControl.length).not.toBe(3);
rewritten

2021-05-05 15:55 UTC, Dev1LtJ approved these changes
ReApproved.

2021-05-05 20:47 UTC, maximsan approved these changes

2021-05-05 20:47 UTC, merged