Review my tasks and validation
Dev-incubator/DIMS.UI-13 pull request #5
Opened 2021-04-09 09:05 UTC by AlexanderRusak

2021-04-25 08:05 UTC, maximsan requested changes
Hello! I left a lot of comments. Most of them can be applied to other places, I didn't repeat it everywhere. Please review them attentively and let me know if you have any questions. I'm closing this P-R because there are bunch of notes. Please open a new one with all fixes. Thanks!

2021-04-25 08:05 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +import { PROGRESS } from '../../db/tableName'; */
remove

2021-04-25 08:05 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +              onKeyPress={() => {}}
use `noop` helper

2021-04-25 08:05 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +  };
it looks like separate component

2021-04-25 08:05 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +            <Button className={classes.warning} onClick={() => this.openModal('edit', index)}>
create method

2021-04-25 08:05 UTC, maximsan commented on src/pages/Members/MemberTracks.jsx
> +  );
it looks like separate component

2021-04-25 08:05 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +        <Button onClick={() => this.openModalHandler('create')} className={`${classes.default} ${classes.pushRight}`}>
create method

2021-04-25 08:05 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +                this.openModalHandler('details');
create method

2021-04-25 08:05 UTC, maximsan commented on src/pages/Tasks/Tasks.jsx
> +  getTable = (data, index) => {
where is key ?

2021-04-25 08:06 UTC, closed without merging

2021-04-25 08:31 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +    isValid = value.trim() !== '' && isValid;
I've fixed

2021-04-25 08:50 UTC, AlexanderRusak commented on src/components/Footer/Footer.jsx
> +              <FaGithub size={50} color='#fff' />
created constants for colors and size

2021-04-25 09:39 UTC, AlexanderRusak commented on src/components/Footer/Footer.jsx
> +          </a>
created custom component to render Icons  with links and removed links to contant

2021-04-25 09:52 UTC, AlexanderRusak commented on src/components/Footer/Footer.module.css
> +  box-sizing: border-box;
Removed for Footer and Header to one style file

2021-04-25 10:04 UTC, AlexanderRusak commented on src/components/Modal/DeleteModal/DeleteModal.jsx
> +        <Button onClick={() => onDelete(item)}>
created method

2021-04-25 10:12 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const el = element.replace(/\s/g, '');
I need to remove spaces inside Full Name to FullName

2021-04-25 10:42 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    console.log(this.state);
i using that because i need to slit space inside string i removed that to helpers

2021-04-25 10:45 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +      FullName: props.editData.FullName || '',
sure i've rewritten

2021-04-25 11:19 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +          onChange={(event) => this.getValue(event, inputItem.title.trim())}
I rewrite here and in TrackModal

2021-04-25 11:21 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +          key={inputItem.title.toString()}
sure my mistake

2021-04-25 11:41 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +          isError={!touched[el] || data[el] /* && el === 'Email' && validateEmail(data.Email) */}
I'm agree with you isError is stange name to variable for checking is valid input or not. I've renamed to isValid

2021-04-25 11:44 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const userDateObj = { ...this.state };
I need to create new user and push  to DB i think you have meant that this code need in another place?

2021-04-25 11:45 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const { Email: email } = this.state;
Yes of course

2021-04-25 11:48 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    await createNewUser(email, '          ');
i'm have exported method setData from firebase/firebase.js
and push to db MEMBERS it's a constant name of document in DB, userDateObj it's a object of data from modal and email like a key of new user

2021-04-25 11:54 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +  editData: PropTypes.shape(),
ok i have rewritten here and in another places

2021-04-25 12:08 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +          onChange={(event) => this.getValue(event, selectItem.title.trim())}
rebuild

2021-04-25 16:52 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.module.css
> +  color: #fff;
unuseble css i 've remove it

2021-04-25 17:21 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +          onChange={(event) => this.onChangeHandler(event, controlName)}
at this case it's impossible to use only event

2021-04-25 18:03 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +          onChange={(event) => this.onChangeHandler(event, controlName)}
![image](https://user-images.githubusercontent.com/23162691/116004064-bb2ae880-a609-11eb-9293-0e20f24ffb7b.png)

2021-04-25 18:35 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +    const response = await signIn(formControls.email.value, formControls.password.value);
created

2021-04-25 18:36 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +    console.log(formControls.email.value, formControls.password.value);
i've removed all console.log sorry for that but i like to debug my code in this way

2021-04-25 18:36 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +    console.log(this.state);
removed

2021-04-25 18:39 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +    let isValid = true;
i saw this validation way in code of another project of another good developer this way is not usefull to validating form with a lot of input types and i go to another way

2021-04-25 18:51 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +      isFormValid: isValid,
i know that but in this situation it's impossible

2021-04-25 19:02 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +      ],
removed

2021-04-25 19:04 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +export class TasksModal extends Component {
added but in future i will return component))))

2021-04-25 19:05 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +      fakeUsers: [...newUsers],
because i think that that date come from db and this is like current data if i edit and create users i need to copy of list

2021-04-25 19:06 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +        <Label value='dssdsds' title='Name' />
sorry, removed

2021-04-25 19:14 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +  };
removed

2021-04-25 19:14 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +  };
removed

2021-04-25 19:14 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.jsx
> +    console.log(type);
removed

2021-04-25 19:18 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +        Date: props.mode === 'edit' ? props.selectedItem.Date : '',
i read about it and it's possible to do

2021-04-25 19:47 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.module.css
> +    background-color: #fff;
i used it once

2021-04-25 20:11 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +          )}
rewritten

2021-04-26 10:58 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +          )}
i reworked that

2021-04-26 10:59 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +              onChange={(event) => this.onValueHandler(event, 'Task')}
i have created method like you you provided to me

2021-04-26 11:09 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +      Date: false,
created. this case becuse in DB i  using with capitalyze letters.

2021-04-26 11:37 UTC, AlexanderRusak commented on src/components/Navigation/Drawer/Drawer.jsx
> +export default class Drawer extends Component {
rebuild like dump functional component

2021-04-26 11:44 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      role='button'
I'm really don't understand you at this

2021-04-26 11:45 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      type='button'
look upper

2021-04-26 11:54 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +import { PROGRESS } from '../../db/tableName'; */
removed

2021-04-26 12:03 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +              onKeyPress={() => {}}
rewritten in all

2021-04-26 12:04 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +  };
sure removed

2021-04-26 12:44 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +            <Button className={classes.warning} onClick={() => this.openModal('edit', index)}>
created

2021-04-26 12:47 UTC, AlexanderRusak commented on src/pages/Members/MemberTracks.jsx
> +  );
can  i use this method in this component i explain why i have chosen this way

2021-04-26 12:56 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +        <Button onClick={() => this.openModalHandler('create')} className={`${classes.default} ${classes.pushRight}`}>
ok i've created in futere i will do like it

2021-04-26 13:00 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +                this.openModalHandler('details');
created

2021-04-26 13:04 UTC, AlexanderRusak commented on src/pages/Tasks/Tasks.jsx
> +  getTable = (data, index) => {
added

2021-04-26 18:14 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  let isValid = true;
if i set by defult false it's can't working

2021-04-26 18:28 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    this.setState({ [el]: value.target.value, touched: { [el]: true } });
removed console.log

2021-04-28 16:58 UTC, maximsan commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const el = element.replace(/\s/g, '');
why do you have such a case ? Anyway create a helper with clear name for this

2021-04-28 17:00 UTC, maximsan commented on src/components/Auth/Auth.js
> +  let isValid = true;
Than your logic is wrong. I don't see real need to assign isValid to `true` by default.

2021-04-28 17:09 UTC, maximsan commented on src/components/UI/Backdrop/Backdrop.jsx
> +      type='button'
what does it mean?

2021-04-28 17:10 UTC, maximsan commented on src/components/UI/Backdrop/Backdrop.jsx
> +      role='button'
I see )

2021-04-28 17:11 UTC, maximsan commented on src/components/Modal/TrackModal/TrackModal.jsx
> +      Date: false,
in that case rename them there to camelCase too

2021-04-28 17:14 UTC, maximsan commented on src/components/Modal/TasksModal/TasksModal.module.css
> +    background-color: #fff;
what do you mean ? https://www.youtube.com/watch?v=PHO6TBq_auI - look there or read somewhere. You need to learn something new everyday if you want to be a developer.

2021-04-28 17:16 UTC, maximsan commented on src/components/Modal/ModalSignIn.jsx
> +    console.log(formControls.email.value, formControls.password.value);
No problem, but clean up your code before pushing

2021-04-28 17:18 UTC, maximsan commented on src/components/Modal/TasksModal/TasksModal.jsx
> +      fakeUsers: [...newUsers],
I see, but why do you do it twice ? you already edit copied data..

2021-04-28 17:19 UTC, maximsan commented on src/components/Modal/ModalSignIn.jsx
> +      isFormValid: isValid,
why ? everything is possible

2021-04-30 21:37 UTC, AlexanderRusak commented on src/components/Modal/ModalRegisterNewUser.jsx
> +    const el = element.replace(/\s/g, '');
removed

2021-04-30 21:42 UTC, AlexanderRusak commented on src/components/Modal/ModalSignIn.jsx
> +      isFormValid: isValid,
Added

2021-04-30 21:59 UTC, AlexanderRusak commented on src/components/Modal/TasksModal/TasksModal.module.css
> +    background-color: #fff;
learn and little bit used

2021-04-30 22:00 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +      Date: false,
renamed

2021-04-30 22:01 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      role='button'
i removed

2021-04-30 22:01 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      type='button'
removed

2021-04-30 22:02 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      aria-label='button'
i understand

2021-04-30 22:02 UTC, AlexanderRusak commented on src/components/UI/Backdrop/Backdrop.jsx
> +      tabIndex={0}
i understand

2021-04-30 22:02 UTC, AlexanderRusak commented on src/components/UI/Buttons/Button/Button.jsx
> +      type='button'
i understand

2021-05-01 18:45 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  let isValid = true;
In Field authorization i use it
If I don't pass validation param i don't validate input field this if control that

2021-05-01 18:51 UTC, AlexanderRusak commented on src/components/Auth/Auth.js
> +  let isValid = true;
Also about isValid=true at the first time it's unused but isValid can changes at false

2021-05-01 20:50 UTC, maximsan commented on src/components/Auth/Auth.js
> +  let isValid = true;
ok, I give up.

2021-05-03 09:35 UTC, AlexanderRusak commented on src/components/Modal/TrackModal/TrackModal.jsx
> +        Date: props.mode === 'edit' ? props.selectedItem.Date : '',
componentDidMount